version: '3.8'

services:
  # Serviço do Banco de Dados MongoDB
  mongodb:
    image: mongo:latest
    container_name: mongodb_infra
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

  # Serviço da Aplicação Node.js
  app:
    build: .
    container_name: node_app
    ports:
      - "1100:1100"
    environment:
      # Note que usamos o nome do serviço 'mongodb' em vez de localhost ou host.docker.internal
      MONGO_URI: mongodb://mongodb:27017/infra_docs
      PORT: 1100
      HOST: 0.0.0.0
      # Passando as variáveis do .env para dentro do container
      SECRET: ${SECRET}
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASS: ${EMAIL_PASS}
      APP_NAME: ${APP_NAME}
    depends_on:
      - mongodb
    restart: always

volumes:
  mongo_data:
